#include		"Chords.hh"

Chords::Chords()
{
  std::vector<char>	chord;
  std::vector<char>	scale;

  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(G));
  _chords[C] = std::make_pair(chord, scale); 
  chord.clear();
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(G));
  _chords[Cm] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(FS));
  _chords[Cdim] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(G));
  _chords[Csus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(GS));
  _chords[Cplus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(G));
  _chords[C4] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(A));
  _chords[C6] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(AS));
  _chords[C7] = std::make_pair(chord, scale);

  chord.clear();
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(GS));
  _chords[CS] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(GS));
  _chords[CSm] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(G));
  _chords[CSdim] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(GS));
  _chords[CSsus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(A));
  _chords[CSplus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(GS));
  _chords[CS4] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(AS));
  _chords[CS6] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(B));
  _chords[CS7] = std::make_pair(chord, scale);

  chord.clear();
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(A));
  _chords[D] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(A));
  _chords[Dm] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(GS));
  _chords[Ddim] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(A));
  _chords[Dsus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(AS));
  _chords[Dplus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(A));
  _chords[D4] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(B));
  _chords[D6] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(C));
  _chords[D7] = std::make_pair(chord, scale);

  chord.clear();
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(AS));
  _chords[DS] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(AS));
  _chords[DSm] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(A));
  _chords[DSdim] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(AS));
  _chords[DSsus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(B));
  _chords[DSplus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(AS));
  _chords[DS4] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(C));
  _chords[DS6] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(CS));
  _chords[DS7] = std::make_pair(chord, scale);

  chord.clear();
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(B));
  _chords[E] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(B));
  _chords[Em] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(AS));
  _chords[Edim] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(B));
  _chords[Esus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(C));
  _chords[Eplus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(B));
  _chords[E4] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(CS));
  _chords[E6] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(D));
  _chords[E7] = std::make_pair(chord, scale);

  chord.clear();
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(C));
  _chords[F] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(C));
  _chords[Fm] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(B));
  _chords[Fdim] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(C));
  _chords[Fsus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(CS));
  _chords[Fplus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(C));
  _chords[F4] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(D));
  _chords[F6] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(DS));
  _chords[F7] = std::make_pair(chord, scale);

  chord.clear();
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(CS));
  _chords[FS] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(CS));
  _chords[FSm] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(C));
  _chords[FSdim] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(CS));
  _chords[FSsus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(D));
  _chords[FSplus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(CS));
  _chords[FS4] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(DS));
  _chords[FS6] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(E));
  _chords[FS7] = std::make_pair(chord, scale);

  chord.clear();
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(D));
  _chords[G] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(D));
  _chords[Gm] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(CS));
  _chords[Gdim] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(D));
  _chords[Gsus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(DS));
  _chords[Gplus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(D));
  _chords[G4] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(E));
  _chords[G6] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(G));
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(F));
  _chords[G7] = std::make_pair(chord, scale);

  chord.clear();
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(DS));
  _chords[GS] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(DS));
  _chords[GSm] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(D));
  _chords[GSdim] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(DS));
  _chords[GSsus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(E));
  _chords[GSplus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(DS));
  _chords[GS4] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(F));
  _chords[GS6] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(GS));
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(FS));
  _chords[GS7] = std::make_pair(chord, scale);

  chord.clear();
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(E));
  _chords[A] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(E));
  _chords[Am] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(C));
  chord.push_back(static_cast<char>(DS));
  _chords[Adim] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(E));
  _chords[Asus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(F));
  _chords[Aplus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(E));
  _chords[A4] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(FS));
  _chords[A6] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(A));
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(G));
  _chords[A7] = std::make_pair(chord, scale);

  chord.clear();
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(F));
  _chords[AS] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(F));
  _chords[ASm] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(CS));
  chord.push_back(static_cast<char>(E));
  _chords[ASdim] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(F));
  _chords[ASsus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(FS));
  _chords[ASplus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(F));
  _chords[AS4] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(G));
  _chords[AS6] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(AS));
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(F));
  chord.push_back(static_cast<char>(GS));
  _chords[AS7] = std::make_pair(chord, scale);

  chord.clear();
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(FS));
  _chords[B] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(FS));
  _chords[Bm] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(D));
  chord.push_back(static_cast<char>(F));
  _chords[Bdim] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(FS));
  _chords[Bsus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(G));
  _chords[Bplus] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(E));
  chord.push_back(static_cast<char>(FS));
  _chords[B4] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(GS));
  _chords[B6] = std::make_pair(chord, scale);
  chord.clear();
  chord.push_back(static_cast<char>(B));
  chord.push_back(static_cast<char>(DS));
  chord.push_back(static_cast<char>(FS));
  chord.push_back(static_cast<char>(A));
  _chords[B7] = std::make_pair(chord, scale);
}

Chords::~Chords()
{

}

std::vector<char>	Chords::getChordFromName(const char name)
{
  return (_chords[name].first);
}

std::vector<char>	Chords::getScaleFromName(const char name)
{
  return (_chords[name].second);
}

int			main()
{
  Chords		test;

  return (0);
}
