# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Barde' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Barde
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'
  pod 'ReachabilitySwift'
  pod 'Starscream', '~> 3.0.2'
  pod 'RxStarscream'
  pod 'SwiftSocket'

end
